export const DEMO_AGENTS = [
  {
    id: 'demo-cos',
    name: 'Chief of Staff',
    icon: '🧠',
    role: 'Chief of Staff',
    title: 'AI Chief of Staff',
    status: 'active',
    description: 'Orchestrates all agents, manages priorities and daily operations.',
    model: 'claude-sonnet-4-6',
    adapterType: 'openclaw',
    budgetMonthlyCents: 5000,
    spentMonthlyCents: 1240,
    color: '#6366f1',
  },
  {
    id: 'demo-dev',
    name: 'Developer',
    icon: '💻',
    role: 'Developer',
    title: 'Full-Stack Developer Agent',
    status: 'running',
    description: 'Writes, reviews and deploys code across the stack.',
    model: 'claude-sonnet-4-6',
    adapterType: 'openclaw',
    budgetMonthlyCents: 8000,
    spentMonthlyCents: 3100,
    color: '#10b981',
  },
  {
    id: 'demo-research',
    name: 'Researcher',
    icon: '🔬',
    role: 'Researcher',
    title: 'Research & Analysis Agent',
    status: 'idle',
    description: 'Deep research, data analysis and strategic insights.',
    model: 'claude-opus-4-7',
    adapterType: 'openclaw',
    budgetMonthlyCents: 10000,
    spentMonthlyCents: 820,
    color: '#f59e0b',
  },
  {
    id: 'demo-writer',
    name: 'Content Writer',
    icon: '✍️',
    role: 'Writer',
    title: 'Content & Copywriting Agent',
    status: 'active',
    description: 'Creates content, copy, docs and marketing material.',
    model: 'claude-haiku-4-5-20251001',
    adapterType: 'openclaw',
    budgetMonthlyCents: 3000,
    spentMonthlyCents: 540,
    color: '#ec4899',
  },
]
